spring:
  application:
    name: AUTH

  datasource:
    jdbc-url: jdbc:h2:mem:testauthdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30

    h2:
      console:
        enabled: true

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true

  zipkin:
    base-url: http://localhost:9411

datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/apidb
  #username: airflow
  #password: airflow
  username: ${db_username}
  password: ${db_password}
  driver-class-name: org.postgresql.Driver
  pool-size: 30
  #ddl-auto: update
  generate-ddl: true
  hibernate:
    ddl-auto: update


# TODO(externalize config)
ldap:
  url: ldap://localhost:10389
  base: dc=company,dc=com
  #userDn: ou=users,
  #username: cn=Manager,dc=maxcrc,dc=com
  #password: secret

#server:
#  port: 8090

jwt:
  secret: secret

security:
  basic:
    enabled: false
  ignored: /**

management:
  security:
    enabled: false